# Dockerfile.newspaper_spider
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

# Create the directory for the SQLite database
RUN mkdir -p /app/newspaper_rss

CMD ["scrapy", "crawl", "newspaper_spider"]
